# Generated by Django 5.0 on 2024-06-03 11:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0005_feedbacks_category_feedbacks_system_and_more'),
        ('pipefy', '0007_remove_card_prospects_phase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Glebas_Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gleba', models.CharField(max_length=255, null=True, verbose_name='Identificação da Gleba')),
                ('area', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Área da Gleba')),
                ('descricao', models.TextField(default=None, null=True, verbose_name='Descrição da Gleba')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipefy.cadastro_pessoal', verbose_name='Cliente')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.municipios', verbose_name='Município')),
                ('propriedade', models.ManyToManyField(to='pipefy.imoveis_rurais', verbose_name='Fazendas')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name_plural': 'Glebas e Áreas',
            },
        ),
        migrations.CreateModel(
            name='Glebas_Coordenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_gd', models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Latitude GD')),
                ('longitude_gd', models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Longitude GD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gleba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glebas.glebas_areas', verbose_name='Gleba')),
            ],
            options={
                'verbose_name_plural': 'Coordenadas Glebas',
            },
        ),
    ]
