# Generated by Django 5.0 on 2024-06-20 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Glebas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('gleba', models.CharField(max_length=255, null=True, verbose_name='Identificação da Gleba')),
                ('area', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Área da Gleba')),
                ('descricao', models.TextField(default=None, null=True, verbose_name='Descrição da Gleba')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('propriedades', models.ManyToManyField(to='farms.imoveis_rurais', verbose_name='Fazendas')),
            ],
            options={
                'verbose_name_plural': 'Cadastro Glebas',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_Glebas_Coordenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('latitude_gd', models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Latitude GD')),
                ('longitude_gd', models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Longitude GD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gleba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glebas.cadastro_glebas', verbose_name='Gleba')),
            ],
            options={
                'verbose_name_plural': 'Coordenadas Glebas',
            },
        ),
    ]
