# Generated by Django 5.0 on 2024-06-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glebas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Culturas_Agricolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cultura', models.CharField(max_length=255, null=True, verbose_name='Cultura Agrícola')),
                ('nome_cientifico', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nome Científico')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Culturas Agrícolas',
            },
        ),
    ]
