# Generated by Django 5.0 on 2024-04-23 08:16

import cadastro.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipefy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotos_Maquinas_Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descrição')),
                ('file', models.FileField(null=True, upload_to='maquinas', verbose_name='Foto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fotos - Máquinas e Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='Municipios',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Código Município')),
                ('cod_uf', models.IntegerField(verbose_name='Código UF')),
                ('sigla_uf', models.CharField(max_length=2, null=True, verbose_name='Sigla UF')),
                ('nome_uf', models.CharField(max_length=255, null=True, verbose_name='Nome UF')),
                ('nome_municipio', models.CharField(max_length=255, null=True, verbose_name='Nome Município')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Municípios',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Benfeitorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Maquina_Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descrição Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo Máquina ou Equipamento',
            },
        ),
        migrations.CreateModel(
            name='Benfeitorias_Fazendas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tamanho', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Tamanho (m²)')),
                ('valor_estimado', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor Estimado (R$)')),
                ('data_construcao', models.DateField(verbose_name='Data Construção')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('farm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipefy.imoveis_rurais', verbose_name='Fazenda')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.tipo_benfeitorias', verbose_name='Tipo de Benfeitoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pictures_Benfeitorias',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(null=True, upload_to=cadastro.models.upload_to_picture_benfeitoria, verbose_name='Fotos')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('benfeitoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.benfeitorias_fazendas')),
                ('upload_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Maquinas_Equipamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('quantidade', models.IntegerField(default=1, null=True, verbose_name='Quantidade')),
                ('ano_fabricacao', models.IntegerField(null=True, verbose_name='Ano Fabricação')),
                ('fabricante', models.CharField(max_length=255, null=True, verbose_name='Fabricante')),
                ('modelo', models.CharField(max_length=255, null=True, verbose_name='Modelo da Máquina ou Equipamento')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor Total da Máquina ou Equipamento')),
                ('situacao', models.CharField(max_length=1, null=True, verbose_name='Situação')),
                ('cor', models.CharField(max_length=50, null=True, verbose_name='Cor da Máquina ou Equipamento')),
                ('serie_chassi', models.CharField(max_length=255, null=True, verbose_name='N° Chassi ou Série')),
                ('potencia_capacidade', models.CharField(max_length=255, null=True, verbose_name='Potência ou Capacidade')),
                ('propriedade', models.CharField(max_length=255, null=True, verbose_name='Imóvel Rural')),
                ('estado_conservacao', models.CharField(max_length=50, null=True, verbose_name='Estado Conservação')),
                ('participacao', models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Percentual Participação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proprietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipefy.cadastro_pessoal', verbose_name='Nome Proprietário')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.tipo_maquina_equipamento', verbose_name='Tipo Máquina')),
            ],
            options={
                'verbose_name_plural': 'Máquinas e Equipamentos',
            },
        ),
    ]
