# Generated by Django 5.0 on 2024-04-23 14:54

import cadastro.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
        ('pipefy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Analise_Solo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data_coleta', models.DateField(verbose_name='Data Coleta')),
                ('identificacao_amostra', models.CharField(max_length=255, null=True, verbose_name='Identificação Amostra')),
                ('profundidade', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Profundidade (cm)')),
                ('numero_controle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Número da amostra')),
                ('latitude_gd', models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Latitude (GD)')),
                ('longitude_gd', models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Longitude (GD)')),
                ('responsavel', models.CharField(max_length=255, null=True, verbose_name='Responsável pela coleta')),
                ('laboratorio_analise', models.CharField(max_length=255, null=True, verbose_name='Laboratório da análise')),
                ('calcio_cmolc_dm3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cálcio')),
                ('magnesio_cmolc_dm3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Magnésio')),
                ('aluminio_cmolc_dm3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Alumínio')),
                ('potassio_cmolc_dm3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Potássio')),
                ('fosforo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Fósforo')),
                ('fosforo_rem', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Fósforo rem')),
                ('enxofre', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Enxofre')),
                ('zinco', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Zinco')),
                ('boro', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Boro')),
                ('cobre', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Cobre')),
                ('ferro', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ferro')),
                ('manganes', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Manganês')),
                ('ph_h2O', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ph em Água')),
                ('ph_cacl2', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='')),
                ('h_mais_al', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='')),
                ('sodio', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='')),
                ('mat_org_dag_dm3', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Matéria Orgânica (dag/dm3)')),
                ('argila_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Argila (%)')),
                ('silte_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Silte (%)')),
                ('areia_percentual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Areia (%)')),
                ('file', models.FileField(blank=True, null=True, upload_to=cadastro.models.upload_to_analise, verbose_name='Arquivo em PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipefy.cadastro_pessoal', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fazenda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipefy.imoveis_rurais', verbose_name='Fazenda')),
            ],
        ),
    ]
