# Generated by Django 5.0 on 2024-06-20 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='analise_solo',
            name='fazenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.imoveis_rurais', verbose_name='Fazenda'),
        ),
        migrations.AddField(
            model_name='benfeitorias_fazendas',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='benfeitorias_fazendas',
            name='farm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.imoveis_rurais', verbose_name='Fazenda'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado Por'),
        ),
        migrations.AddField(
            model_name='analise_solo',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='cartorios_registro',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='categoria_cadastro',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado Por'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoal',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.categoria_cadastro', verbose_name='Categoria Cadastro'),
        ),
        migrations.AddField(
            model_name='contas_bancarias_clientes',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal'),
        ),
        migrations.AddField(
            model_name='contas_bancarias_clientes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='culturas_agricolas',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado Por'),
        ),
        migrations.AddField(
            model_name='detalhamento_servicos',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresas_frasson',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='empresas_frasson',
            name='socios',
            field=models.ManyToManyField(to='cadastro.cadastro_pessoal', verbose_name='Sócios'),
        ),
        migrations.AddField(
            model_name='feedbacks_system',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.feedbacks_category', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='feedbacks_system',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='feedbacks_replies',
            name='feedback',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.feedbacks_system', verbose_name='Feedback'),
        ),
        migrations.AddField(
            model_name='fotos_maquinas_equipamentos',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by'),
        ),
        migrations.AddField(
            model_name='grupos_clientes',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado Por'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoal',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.grupos_clientes', verbose_name='Id do Grupo'),
        ),
        migrations.AddField(
            model_name='instituicoes_parceiras',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contas_bancarias_clientes',
            name='instituicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.instituicoes_parceiras'),
        ),
        migrations.AddField(
            model_name='instituicoes_razao_social',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instituicoes_parceiras',
            name='instituicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.instituicoes_razao_social'),
        ),
        migrations.AddField(
            model_name='maquinas_equipamentos',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='maquinas_equipamentos',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Nome Proprietário'),
        ),
        migrations.AddField(
            model_name='instituicoes_parceiras',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.municipios', verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='empresas_frasson',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.municipios', verbose_name='Municípios'),
        ),
        migrations.AddField(
            model_name='cartorios_registro',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.municipios', verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='cadastro_pessoal',
            name='municipio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.municipios', verbose_name='Município'),
        ),
        migrations.AddField(
            model_name='pictures_benfeitorias',
            name='benfeitoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.benfeitorias_fazendas'),
        ),
        migrations.AddField(
            model_name='pictures_benfeitorias',
            name='upload_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='produtos_frasson',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalhamento_servicos',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.produtos_frasson'),
        ),
        migrations.AddField(
            model_name='senhas_logins',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='senhas_logins',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado Por'),
        ),
        migrations.AddField(
            model_name='senhas_logins',
            name='instituicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.instituicoes_razao_social', verbose_name='Instituição'),
        ),
        migrations.AddField(
            model_name='tipo_benfeitorias',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='benfeitorias_fazendas',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.tipo_benfeitorias', verbose_name='Tipo de Benfeitoria'),
        ),
        migrations.AddField(
            model_name='tipo_instituicao',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='instituicoes_razao_social',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.tipo_instituicao', verbose_name='Tipo Instituição'),
        ),
        migrations.AddField(
            model_name='maquinas_equipamentos',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.tipo_maquina_equipamento', verbose_name='Tipo Máquina'),
        ),
    ]
