# Generated by Django 5.0 on 2024-04-25 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_analise_solo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ver_feedbacks_users', 'Ver Feedbacks Users'), ('ver_cadastros_gerais', 'Ver Cadastros Gerais')],
                'managed': False,
            },
        ),
    ]
