# Generated by Django 5.0 on 2024-08-05 11:54

import cadastro.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_categoria_cadastro_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anexos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(null=True, upload_to=cadastro.models.upload_anexo, verbose_name='Arquivo')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nome Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analise_solo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.analise_solo', verbose_name='Análise Solo')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadupby', to=settings.AUTH_USER_MODEL, verbose_name='Carregado por')),
            ],
            options={
                'verbose_name_plural': 'Anexos Register',
            },
        ),
    ]
