# Generated by Django 5.0 on 2024-05-07 16:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_myapppermissions'),
        ('pipefy', '0007_remove_card_prospects_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agencias_Bancarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao_agencia', models.CharField(max_length=150, null=True, verbose_name='Descrição da Agência')),
                ('numero_agencia', models.CharField(default=None, max_length=30, null=True, verbose_name='Número Agência')),
                ('cep_agencia', models.CharField(default=None, max_length=30, null=True, verbose_name='CEP Agência')),
                ('endereco_agencia', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Endereço Agência')),
                ('telefone_agencia', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Telefone Contato Agência')),
                ('email_agencia', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='E-mail Contato Agência')),
                ('gerente_agencia', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Nome Gerente Agência')),
                ('email_gerente', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='E-mail Gerente Agência')),
                ('telefone_gerente', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Telefone Gerente Agência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipefy.instituicoes_razao_social', verbose_name='Instituição')),
                ('municipio_agencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.municipios', verbose_name='Município Agência')),
            ],
            options={
                'verbose_name_plural': 'Agências Bancárias',
            },
        ),
    ]
