# Generated by Django 5.0 on 2024-08-06 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_anexos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analise_solo',
            name='file',
        ),
    ]
