# Generated by Django 5.0 on 2024-10-14 08:26

import custompipeline.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=custompipeline.models.gerarcode, unique=True)),
                ('data', models.JSONField(null=True, verbose_name='Dados Card')),
                ('data_vencimento', models.DateTimeField(null=True, verbose_name='Data de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Nome Fase')),
                ('dias_prazo', models.IntegerField(null=True)),
                ('propriedades', models.JSONField(null=True, verbose_name='Propriedades Fluxo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_fase', to=settings.AUTH_USER_MODEL)),
                ('destinos_permitidos', models.ManyToManyField(blank=True, related_name='fases_origem', to='custompipeline.fase')),
                ('responsaveis', models.ManyToManyField(related_name='responsaveis_fase_custom', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
            ],
            options={
                'verbose_name_plural': 'Fases',
            },
        ),
        migrations.CreateModel(
            name='Card_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField(null=True, verbose_name='Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custompipeline.card', verbose_name='Card')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by_2', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custompipeline.fase', verbose_name='Fase')),
            ],
            options={
                'verbose_name_plural': 'Comentários Card',
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=custompipeline.models.gerarcode, unique=True)),
                ('tipo', models.CharField(choices=[('TC', 'Texto Curto'), ('TC', 'Texto Longo'), ('N', 'Numérico'), ('A', 'Anexo'), ('D', 'Data'), ('DH', 'Data e Hora'), ('CF', 'Conexão de Fluxo'), ('CD', 'Conexão de Database'), ('CB', 'Checkbox')], max_length=5, null=True, verbose_name='Tipo')),
                ('propriedades', models.JSONField(null=True, verbose_name='Propriedades Campo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custompipeline.fase')),
            ],
            options={
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.CreateModel(
            name='Card_Anexos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(null=True, upload_to='custompipeline', verbose_name='Arquivo')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Nome Arquivo')),
                ('propriedades', models.JSONField(null=True, verbose_name='Propriedades Anexo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custompipeline.card', verbose_name='Fluxo')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_by', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custompipeline.field', verbose_name='Produto')),
            ],
            options={
                'verbose_name_plural': 'Anexos Card',
            },
        ),
        migrations.CreateModel(
            name='Card_Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('ch', 'change'), ('co', 'comment'), ('mv', 'fase'), ('c', 'concluiu')], max_length=60, null=True, verbose_name='Tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custompipeline.card', verbose_name='Card')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_by', to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('campo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custompipeline.field', verbose_name='Campo')),
            ],
            options={
                'verbose_name_plural': 'Atividades Card',
            },
        ),
        migrations.CreateModel(
            name='Fluxo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=custompipeline.models.gerarcode, unique=True)),
                ('nome', models.CharField(max_length=255, verbose_name='Descricao Fluxo')),
                ('propriedades', models.JSONField(null=True, verbose_name='Propriedades Fluxo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pessoas', models.ManyToManyField(related_name='pessoas_autorizadas_custom', to=settings.AUTH_USER_MODEL, verbose_name='Pessoas Autorizadas')),
            ],
            options={
                'verbose_name_plural': 'Pipe',
            },
        ),
        migrations.AddField(
            model_name='field',
            name='fluxo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custompipeline.fluxo'),
        ),
        migrations.AddField(
            model_name='fase',
            name='fluxo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custompipeline.fluxo'),
        ),
        migrations.CreateModel(
            name='Phases_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=custompipeline.models.gerarcode, unique=True)),
                ('first_time_in', models.DateTimeField(null=True)),
                ('last_time_in', models.DateTimeField(null=True)),
                ('last_time_out', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custompipeline.card', verbose_name='Card')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moved_by', to=settings.AUTH_USER_MODEL, verbose_name='Movido por')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custompipeline.fase', verbose_name='Fase')),
            ],
            options={
                'verbose_name_plural': 'Histórico de Fases',
            },
        ),
        migrations.CreateModel(
            name='Relacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=custompipeline.models.gerarcode, unique=True)),
                ('to_table', models.CharField(max_length=30, null=True, verbose_name='Nome Database')),
                ('propriedades', models.JSONField(null=True, verbose_name='Propriedades Relação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='custompipeline.field')),
                ('from_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_card', to='custompipeline.card')),
                ('to_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_card', to='custompipeline.card')),
                ('to_fluxo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_fluxo', to='custompipeline.fluxo')),
            ],
            options={
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
