# Generated by Django 5.0 on 2024-04-23 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipefy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ver_administrator', 'Ver Administrator Panel')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Testes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipefy.pipe', verbose_name='Pipe testado')),
            ],
        ),
    ]
