# Generated by Django 5.0 on 2024-05-09 11:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('gerenciar_kpis', 'Gerenciar KPIs')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicadores_Frasson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descrição Indicador')),
                ('polarity', models.BooleanField(default=True, null=True, verbose_name='Polaridade do Indicador')),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Indicadores Frasson',
            },
        ),
        migrations.CreateModel(
            name='Metas_Realizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Ano')),
                ('target_january', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Meta Janeiro')),
                ('actual_january', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Realizado Janeiro')),
                ('target_february', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Meta Fevereiro')),
                ('actual_february', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Realizado Fevereiro')),
                ('target_march', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Meta Março')),
                ('actual_march', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Realizado Março')),
                ('target_april', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Meta Abril')),
                ('actual_april', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Realizado Abril')),
                ('target_may', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Meta Maio')),
                ('actual_may', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Realizado Maio')),
                ('target_june', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Meta Junho')),
                ('actual_june', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Realizado Junho')),
                ('target_july', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Meta Julho')),
                ('actual_july', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Realizado Julho')),
                ('target_august', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Meta Agosto')),
                ('actual_august', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Realizado Agosto')),
                ('target_september', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Meta Setembro')),
                ('actual_september', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Realizado Setembro')),
                ('target_october', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Meta Outubro')),
                ('actual_october', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Realizado Outubro')),
                ('target_november', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Meta Novembro')),
                ('actual_november', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Realizado Novembro')),
                ('target_december', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Meta Dezembro')),
                ('actual_december', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Realizado Dezembro')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.indicadores_frasson', to_field='uuid', verbose_name='Indicador')),
            ],
            options={
                'verbose_name_plural': 'Metas e Realizados Frasson',
            },
        ),
    ]
