# Generated by Django 5.0 on 2024-06-20 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('gerenciar_kpis', 'Gerenciar KPIs')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Indicadores_Frasson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descrição Indicador')),
                ('polarity', models.BooleanField(default=True, null=True, verbose_name='Polaridade do Indicador')),
                ('is_active', models.BooleanField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Indicadores Frasson',
            },
        ),
        migrations.CreateModel(
            name='Metas_Realizados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Ano')),
                ('month', models.IntegerField(null=True, verbose_name='Mês')),
                ('target', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Meta Mês')),
                ('actual', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True, verbose_name='Realizado Mês')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsável')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kpi.indicadores_frasson', to_field='uuid', verbose_name='Indicador')),
            ],
            options={
                'verbose_name_plural': 'Metas e Realizados Frasson',
            },
        ),
    ]
