# Generated by Django 5.0 on 2024-06-20 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0002_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itens_Financiados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('item', models.CharField(max_length=255, null=True, verbose_name='Item Financiado')),
                ('tipo', models.CharField(max_length=255, null=True, verbose_name='Tipo Item Financiado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cadastro de Itens Financiados',
            },
        ),
        migrations.CreateModel(
            name='Operacoes_Contratadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_operacao', models.CharField(max_length=255, null=True, verbose_name='Número da Operação')),
                ('valor_operacao', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor da Operação')),
                ('area_beneficiada', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Área Total Beneficiada')),
                ('quantidade_kg', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Quantidade em Kg')),
                ('varidade_semente', models.CharField(max_length=255, null=True, verbose_name='Variedade Semente')),
                ('prod_esperada_kg_ha', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Produtividade Esperada')),
                ('adubacao_total', models.TextField(null=True, verbose_name='Adubação Total')),
                ('fonte_recurso', models.CharField(max_length=255, null=True, verbose_name='Fonte do Recurso')),
                ('data_emissao_cedula', models.DateField(null=True, verbose_name='Data Emissão Cédula')),
                ('data_primeiro_vencimento', models.DateField(null=True, verbose_name='Data Primeiro Vencimento')),
                ('data_prod_armazenado', models.DateField(null=True, verbose_name='Data Prod. Armazenado')),
                ('data_vencimento', models.DateField(null=True, verbose_name='Data Vencimento')),
                ('taxa_juros', models.DecimalField(decimal_places=4, max_digits=10, null=True, verbose_name='Taxa Juros')),
                ('safra', models.CharField(max_length=50, null=True, verbose_name='Safra')),
                ('garantia', models.TextField(null=True, verbose_name='Garantia')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Beneficiário')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('imoveis_beneficiados', models.ManyToManyField(to='farms.imoveis_rurais', verbose_name='Imóvel Beneficiado')),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.instituicoes_parceiras', verbose_name='Instituição Parceira')),
                ('item_financiado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.itens_financiados', verbose_name='Item Financiado')),
            ],
            options={
                'verbose_name_plural': 'Operações Contratadas',
            },
        ),
        migrations.CreateModel(
            name='Operacoes_Contratadas_Cedulas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(null=True, upload_to='credit/cedulas', verbose_name='Arquivo PDF Cédula')),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('operacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.operacoes_contratadas')),
                ('upload_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cédulas Operações',
            },
        ),
        migrations.CreateModel(
            name='Operacoes_Contratadas_Glebas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('latitude_gd', models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Latitude GD')),
                ('longitude_gd', models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Longitude GD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('operacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='credit.operacoes_contratadas', verbose_name='Gleba')),
            ],
            options={
                'verbose_name_plural': 'Coordenadas Glebas Operações',
            },
        ),
    ]
