# Generated by Django 5.0 on 2024-07-01 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao_Colaboradores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=150, null=True, verbose_name='Descrição')),
                ('data_ref', models.DateField(null=True)),
                ('is_active', models.BooleanField(default=True, null=True, verbose_name='Ativo?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colaboradores', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Colaboradores a Avaliar')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category_Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=150, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('Q', 'Qualitativo'), ('N', 'Quantitativo')], max_length=1, null=True, verbose_name='Tipo do critério')),
                ('text', models.TextField(null=True, verbose_name='Texto da pergunta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessments.category_avaliacao', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notas_Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nota', models.IntegerField(null=True, verbose_name='Nota da avaliação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avaliacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.avaliacao_colaboradores', verbose_name='Avaliação')),
                ('avaliado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avaliado', to=settings.AUTH_USER_MODEL, verbose_name='Avaliado')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ponderador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ponderador', to=settings.AUTH_USER_MODEL, verbose_name='Quem avalia')),
                ('questionario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.questionario', verbose_name='Questionário')),
            ],
        ),
    ]
