# Generated by Django 5.0 on 2024-05-10 15:31

import django.db.models.deletion
import environmental.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_agencias_bancarias'),
        ('environmental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas_Consultoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('razao_social', models.CharField(max_length=255, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(blank=True, error_messages={'unique': 'CNPJ já cadastrado!'}, max_length=40, null=True, unique=True, verbose_name='CNPJ')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço Empresa')),
                ('contato_telefone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato Telefone')),
                ('contato_email', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato Email')),
                ('responsavel', models.CharField(blank=True, max_length=255, null=True, verbose_name='Contato Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.municipios', verbose_name='Município')),
            ],
            options={
                'verbose_name_plural': 'Empresas Consultoria',
            },
        ),
        migrations.CreateModel(
            name='Processos_ASV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processo', models.CharField(error_messages={'unique': 'Processo já cadastrado!'}, max_length=255, null=True, unique=True, verbose_name='Número Processo')),
                ('requerente', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Requerente')),
                ('cpf_cnpj', models.CharField(blank=True, max_length=40, null=True, verbose_name='CPF/CNPJ')),
                ('portaria', models.CharField(blank=True, max_length=30, null=True, verbose_name='Portaria')),
                ('data_publicacao', models.DateField(blank=True, null=True, verbose_name='Data Publicação')),
                ('data_vencimento', models.DateField(blank=True, null=True, verbose_name='Data Publicação')),
                ('area_total', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Área Total ASV')),
                ('localidade', models.CharField(blank=True, max_length=255, null=True, verbose_name='Localidade')),
                ('rendimento', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Rendimento Lenhoso')),
                ('data_formacao', models.DateField(blank=True, null=True, verbose_name='Data Formação')),
                ('tecnico', models.CharField(blank=True, max_length=255, null=True, verbose_name='Técnico responsável')),
                ('file', models.FileField(default=None, null=True, upload_to=environmental.models.upload_to_asv, verbose_name='Arquivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado Por')),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='environmental.empresas_consultoria', verbose_name='Empresa Consultoria')),
                ('municipio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.municipios', verbose_name='Município')),
            ],
            options={
                'verbose_name_plural': 'Processos ASV',
            },
        ),
        migrations.CreateModel(
            name='Processos_ASV_Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacao_area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Identificação da Área')),
                ('file', models.FileField(default=None, null=True, upload_to='inema/asv/kml', verbose_name='Arquivo PDF')),
                ('area_total', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Área Total')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='environmental.processos_asv', verbose_name='Processo ASV')),
            ],
            options={
                'verbose_name_plural': 'Áreas Processos ASV',
            },
        ),
    ]
