# Generated by Django 5.0 on 2024-07-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimentos_appo_coordenadas',
            name='vazao_m3_dia',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Expect. Vazão (m3/dia)'),
        ),
    ]
