# Generated by Django 5.0 on 2024-05-10 15:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environmental', '0002_empresas_consultoria_processos_asv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processos_asv',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
