# Generated by Django 5.0 on 2024-05-07 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operacoes_Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True, verbose_name='Data Alongamento')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Percentual Exigido Alongamento')),
                ('valor_unitario', models.DecimalField(decimal_places=5, max_digits=15, null=True, verbose_name='Valor Unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor Total Alongamento')),
                ('quant_penhor_kg', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Quantidade de Penhor')),
                ('quant_penhor_tons', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Quantidade Penhos Tons')),
                ('quant_sacas_60_kg', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Quantidade Sacas')),
                ('capacidade_estatica_sacas_60_kg', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Capacidade Estática Armazenagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Alongamentos Operações de Crédito',
            },
        ),
        migrations.CreateModel(
            name='Produto_Agricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descrição do Produto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Produtos Agrícolas',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Armazenagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descrição Tipo Armazenagem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo Armazenagem Produto',
            },
        ),
        migrations.CreateModel(
            name='Tipo_Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descrição Tipo Classificação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tipo Classificação Produto',
            },
        ),
    ]
