# Generated by Django 5.0 on 2024-05-07 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alongamentos', '0001_initial'),
        ('cadastro', '0004_agencias_bancarias'),
        ('pipefy', '0007_remove_card_prospects_phase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='operacoes_credito',
            name='agencia_bancaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.agencias_bancarias', verbose_name='Agência Bancária'),
        ),
        migrations.AddField(
            model_name='operacoes_credito',
            name='fiel_depositario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiel_depositario_id', to='pipefy.cadastro_pessoal', verbose_name='Fiel Depositário'),
        ),
        migrations.AddField(
            model_name='operacoes_credito',
            name='municipio_propriedade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.municipios', verbose_name='Município Propriedade'),
        ),
        migrations.AddField(
            model_name='operacoes_credito',
            name='operacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipefy.operacoes_contratadas', verbose_name='Operação de Crédito'),
        ),
        migrations.AddField(
            model_name='operacoes_credito',
            name='propriedade',
            field=models.ManyToManyField(to='pipefy.imoveis_rurais', verbose_name='Imóveis Rurais'),
        ),
        migrations.AddField(
            model_name='operacoes_credito',
            name='testemunha01',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testemunha01_id', to='pipefy.cadastro_pessoal', verbose_name='Testemunha 01'),
        ),
        migrations.AddField(
            model_name='operacoes_credito',
            name='testemunha02',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testemunha02_id', to='pipefy.cadastro_pessoal', verbose_name='Testemunha 01'),
        ),
        migrations.AddField(
            model_name='operacoes_credito',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='operacoes_credito',
            name='produto_agricola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alongamentos.produto_agricola', verbose_name='Produto Agrícola'),
        ),
        migrations.AddField(
            model_name='operacoes_credito',
            name='tipo_armazenagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alongamentos.tipo_armazenagem', verbose_name='Tipo Armazenagem'),
        ),
        migrations.AddField(
            model_name='operacoes_credito',
            name='tipo_classificacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alongamentos.tipo_classificacao', verbose_name='Tipo Classificação'),
        ),
    ]
