# Generated by Django 5.0 on 2024-06-20 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alongamentos', '0001_initial'),
        ('cadastro', '0002_initial'),
        ('credit', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro_alongamentos',
            name='agencia_bancaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.instituicoes_parceiras', verbose_name='Agência Bancária'),
        ),
        migrations.AddField(
            model_name='cadastro_alongamentos',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='cadastro_alongamentos',
            name='fiel_depositario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiel_depositario_id', to='cadastro.cadastro_pessoal', verbose_name='Fiel Depositário'),
        ),
        migrations.AddField(
            model_name='cadastro_alongamentos',
            name='operacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit.operacoes_contratadas', verbose_name='Operação de Crédito'),
        ),
        migrations.AddField(
            model_name='cadastro_alongamentos',
            name='propriedades',
            field=models.ManyToManyField(to='farms.imoveis_rurais', verbose_name='Imóveis Rurais'),
        ),
        migrations.AddField(
            model_name='cadastro_alongamentos',
            name='testemunha01',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testemunha01_id', to='cadastro.cadastro_pessoal', verbose_name='Testemunha 01'),
        ),
        migrations.AddField(
            model_name='cadastro_alongamentos',
            name='testemunha02',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testemunha02_id', to='cadastro.cadastro_pessoal', verbose_name='Testemunha 01'),
        ),
        migrations.AddField(
            model_name='produto_agricola',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='produto_agricola',
            name='cultura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.culturas_agricolas', verbose_name='Cultura'),
        ),
        migrations.AddField(
            model_name='cadastro_alongamentos',
            name='produto_agricola',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alongamentos.produto_agricola', verbose_name='Produto Agrícola'),
        ),
        migrations.AddField(
            model_name='tipo_armazenagem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='cadastro_alongamentos',
            name='tipo_armazenagem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alongamentos.tipo_armazenagem', verbose_name='Tipo Armazenagem'),
        ),
        migrations.AddField(
            model_name='tipo_classificacao',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='cadastro_alongamentos',
            name='tipo_classificacao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alongamentos.tipo_classificacao', verbose_name='Tipo Classificação'),
        ),
    ]
