# Generated by Django 5.0 on 2024-04-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipefy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicoes_parceiras',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='instituicoes_razao_social',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
