# Generated by Django 5.0 on 2024-04-29 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipefy', '0002_alter_instituicoes_parceiras_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fase',
            name='uuid',
        ),
    ]
