# Generated by Django 5.0 on 2024-04-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipefy', '0003_remove_fase_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
