# Generated by Django 5.0 on 2024-04-29 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipefy', '0004_alter_fase_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pipe',
            name='uuid',
        ),
    ]
