# Generated by Django 5.0 on 2024-04-30 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipefy', '0005_remove_pipe_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect_Monitoramento_Prazos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_vencimento', models.DateField(null=True, verbose_name='Data Vencimento')),
                ('description', models.TextField(null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipefy.card_prospects', verbose_name='Prospect')),
            ],
            options={
                'verbose_name_plural': 'Monitoramento Prazos Prospect',
            },
        ),
    ]
