# Generated by Django 5.0 on 2024-05-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_cobrancas_pipefy_phase_and_more'),
        ('pipefy', '0006_prospect_monitoramento_prazos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_prospects',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='card_produtos',
            name='phase',
        ),
        migrations.AddField(
            model_name='card_produtos',
            name='phase_id',
            field=models.BigIntegerField(null=True, verbose_name='Id da Fase Atual'),
        ),
        migrations.AddField(
            model_name='card_produtos',
            name='phase_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome da Fase Atual'),
        ),
        migrations.AddField(
            model_name='card_prospects',
            name='phase_id',
            field=models.BigIntegerField(null=True, verbose_name='Id da Fase Atual'),
        ),
        migrations.AddField(
            model_name='card_prospects',
            name='phase_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome da Fase Atual'),
        ),
        migrations.DeleteModel(
            name='Fase',
        ),
    ]
