# Generated by Django 5.0 on 2024-06-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipefy', '0007_remove_card_prospects_phase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipe',
            options={'verbose_name_plural': 'Cadastro Pipes'},
        ),
        migrations.RemoveField(
            model_name='pipe',
            name='descricao',
        ),
        migrations.AddField(
            model_name='pipe',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Pipe'),
        ),
        migrations.AddField(
            model_name='pipe',
            name='type',
            field=models.CharField(choices=[('D', 'Database'), ('P', 'Pipe')], max_length=1, null=True, verbose_name='Tipo Pipe'),
        ),
        migrations.AlterField(
            model_name='pipe',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
