# Generated by Django 5.0 on 2024-06-06 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipefy', '0008_alter_pipe_options_remove_pipe_descricao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos_Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('A', 'Assinatura Contrato'), ('P', 'Protocolo'), ('E', 'Encerramento')], max_length=1, null=True, verbose_name='Etapa Pagamento')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='percentual')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipefy.contratos_servicos')),
            ],
            options={
                'verbose_name_plural': 'Contratos - Forma Pagamento',
            },
        ),
    ]
