# Generated by Django 5.0 on 2024-06-07 10:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipefy', '0009_contratos_pagamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Ambiental_Rural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_car', models.CharField(blank=True, max_length=150, null=True, verbose_name='Número do CAR')),
                ('area_preservacao_permanente', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Área APP')),
                ('area_uso_restrito', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Área Uso Restrito')),
                ('condicao_cadastro', models.CharField(blank=True, max_length=250, null=True, verbose_name='Condição Cadastro')),
                ('area_imovel', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Área Imóvel')),
                ('modulos_fiscais', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Módulos Fiscais')),
                ('endereco_municipio', models.CharField(blank=True, max_length=250, null=True, verbose_name='Endereço Município')),
                ('endereco_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('endereco_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Longitude')),
                ('data_registro', models.DateField(blank=True, null=True, verbose_name='Data Registro')),
                ('data_analise', models.DateField(blank=True, null=True, verbose_name='Data Análise')),
                ('data_retificacao', models.DateField(blank=True, null=True, verbose_name='Data Retificação')),
                ('reserva_situacao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Reserva Situação')),
                ('reserva_area_averbada', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='RL Área Averbada')),
                ('reserva_area_nao_averbada', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='RL Área Não Averbada')),
                ('reserva_legal_proposta', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='RL Proposta')),
                ('reserva_legal_declarada', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='RL Declarada')),
                ('situacao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Situação CAR')),
                ('solo_area_nativa', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Solo - Área Nativa')),
                ('solo_area_uso', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Solo - Área Uso')),
                ('solo_area_servidao', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Solo - Área Servidão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imovel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipefy.imoveis_rurais', verbose_name='Imóvel Rural')),
            ],
            options={
                'verbose_name_plural': 'Cadastro Ambiental Rural',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_Ambiental_Rural_Coordenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipefy.cadastro_ambiental_rural', verbose_name='Imóvel Rural')),
            ],
            options={
                'verbose_name_plural': 'Coordenadas do CAR',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_Ambiental_Rural_Restricoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origem da Restrição')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Restrição')),
                ('data_processamento', models.DateField(blank=True, null=True, verbose_name='Data Processamento')),
                ('area_conflito', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Área de Conflito')),
                ('percentual', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Percentual Área Conflito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipefy.cadastro_ambiental_rural', verbose_name='Imóvel Rural')),
            ],
            options={
                'verbose_name_plural': 'Restrições no CAR',
            },
        ),
        migrations.CreateModel(
            name='Certificacao_Sigef_Parcelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Imóvel')),
                ('area_ha', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Área Ha')),
                ('detentor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detentor')),
                ('cpf_cnpj_detentor', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF/CNPJ')),
                ('cns', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNS')),
                ('codigo_parcela', models.UUIDField(blank=True, null=True, verbose_name='Código Parcela')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNS')),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('imovel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipefy.imoveis_rurais', verbose_name='Imóvel Rural')),
            ],
            options={
                'verbose_name_plural': 'Parcelas Certificações SIGEF',
            },
        ),
        migrations.CreateModel(
            name='Certificacao_Sigef_Parcelas_Limites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('do_vertice', models.CharField(blank=True, max_length=100, null=True, verbose_name='Do Vértice')),
                ('ao_vertice', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ao Vértice')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('lado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lado')),
                ('azimute', models.CharField(blank=True, max_length=100, null=True, verbose_name='Azimute')),
                ('comprimento', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Comprimento')),
                ('confrontante', models.TextField(blank=True, null=True, verbose_name='Confrontante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipefy.certificacao_sigef_parcelas', verbose_name='Parcela')),
            ],
            options={
                'verbose_name_plural': 'SIGEF - Limites de Parcelas',
            },
        ),
        migrations.CreateModel(
            name='Certificacao_Sigef_Parcelas_Vertices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Vértice')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Longitude')),
                ('sigma_long', models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True, verbose_name='Sigma Long')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('sigma_lat', models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True, verbose_name='Sigma Lat')),
                ('altitude', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Altitude')),
                ('sigma_altitude', models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True, verbose_name='Sigma Altitude')),
                ('metodo_posicionamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Método Posicionamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipefy.certificacao_sigef_parcelas', verbose_name='Parcela')),
            ],
            options={
                'verbose_name_plural': 'SIGEF - Vértices de Parcelas',
            },
        ),
    ]
