# Generated by Django 5.0 on 2024-07-01 10:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0002_initial'),
        ('glebas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producao_Agricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('variedade', models.CharField(max_length=150, null=True, verbose_name='Variedade Cultura')),
                ('safra', models.CharField(blank=True, max_length=255, null=True, verbose_name='Safra')),
                ('plantio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meses Plantio')),
                ('colheita', models.CharField(blank=True, max_length=255, null=True, verbose_name='Meses Colheita')),
                ('prod_prevista_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Produção Prevista em kg')),
                ('prod_obtida_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Produção Obtida em kg')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('cultura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.culturas_agricolas', verbose_name='Cultura')),
                ('gleba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glebas.cadastro_glebas', verbose_name='Gleba')),
            ],
            options={
                'verbose_name_plural': 'Produção Agrícola',
            },
        ),
        migrations.CreateModel(
            name='Produto_Principal_Pecuaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=250, verbose_name='Produto Principal Pecuária')),
                ('sigla', models.CharField(max_length=100, verbose_name='Sigla Produto Principal Pecuária')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name_plural': 'Produto Principal Pecuária',
            },
        ),
        migrations.CreateModel(
            name='Sistema_Producao_Pecuaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=250, verbose_name='Descrição Sistema Produção')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name_plural': 'Sistema Produção Pecuária',
            },
        ),
        migrations.CreateModel(
            name='Unidade_Producao_Pecuaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.CharField(max_length=250, verbose_name='Descrição Unidade Produção')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name_plural': 'Unidade Produção Pecuária',
            },
        ),
        migrations.CreateModel(
            name='Producao_Pecuaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_producao', models.CharField(choices=[('P', 'Prevista'), ('O', 'Obtida')], max_length=1, null=True, verbose_name='Tipo Produção')),
                ('ano', models.IntegerField(null=True, verbose_name='Ano')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Quantidade')),
                ('produtos_secundarios', models.TextField(blank=True, null=True, verbose_name='Produtos Secundários')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('file', models.FileField(default=None, null=True, upload_to='litecs/pecuaria', verbose_name='Arquivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('gleba', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='glebas.cadastro_glebas', verbose_name='Gleba')),
                ('produto_principal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='litec.produto_principal_pecuaria', verbose_name='Produto Principal Pecuária')),
                ('sistema_producao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='litec.sistema_producao_pecuaria', verbose_name='Sistema Produção Pecuária')),
                ('unidade_producao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='litec.unidade_producao_pecuaria', verbose_name='Unidade Produção Pecuária')),
            ],
            options={
                'verbose_name_plural': 'Produção Pecuária',
            },
        ),
    ]
