# Generated by Django 5.0 on 2024-07-01 10:46

import django.db.models.deletion
import pipeline.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0002_initial'),
        ('finances', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Nome Fase')),
                ('dias_prazo', models.IntegerField(null=True)),
                ('done', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('responsaveis', models.ManyToManyField(related_name='responsaveis_fase', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
            ],
            options={
                'verbose_name_plural': 'Fases',
                'ordering': ['done', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Fluxo_Gestao_Ambiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('prioridade', models.CharField(max_length=255, null=True, verbose_name='Prioridade')),
                ('data_vencimento', models.DateTimeField(null=True, verbose_name='Data de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Nome Beneficiário')),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.contratos_ambiental', verbose_name='Contrato Serviço')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('detalhamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.detalhamento_servicos', verbose_name='Detalhamento Serviço')),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.instituicoes_parceiras', verbose_name='Instituição Parceira')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fase', verbose_name='Fase')),
                ('responsaveis', models.ManyToManyField(related_name='responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
            ],
            options={
                'verbose_name_plural': 'Fluxo Gestão Ambiental',
            },
        ),
        migrations.CreateModel(
            name='Fluxo_Gestao_Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('prioridade', models.CharField(max_length=255, null=True, verbose_name='Prioridade')),
                ('data_vencimento', models.DateTimeField(null=True, verbose_name='Data de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiarios', models.ManyToManyField(to='cadastro.cadastro_pessoal', verbose_name='Nome Beneficiário')),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.contratos_credito', verbose_name='Contrato Serviço')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('detalhamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.detalhamento_servicos', verbose_name='Detalhamento Serviço')),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.instituicoes_parceiras', verbose_name='Instituição Parceira')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fase', verbose_name='Fase')),
                ('responsaveis', models.ManyToManyField(related_name='responsaveis2', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
            ],
            options={
                'verbose_name_plural': 'Fluxo Gestão Crédito',
            },
        ),
        migrations.CreateModel(
            name='Fluxo_Prospects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('produto', models.CharField(max_length=255, null=True, verbose_name='Produto de Interesse')),
                ('classificacao', models.CharField(max_length=255, null=True, verbose_name='Classificação do Prospect')),
                ('origem', models.CharField(max_length=255, null=True, verbose_name='Origem do Prospect')),
                ('proposta_inicial', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Proposta Inicial')),
                ('proposta_aprovada', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Proposta Aprovada')),
                ('percentual_inicial', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Percentual Inicial')),
                ('percentual_aprovado', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Percentual Aprovado')),
                ('data_vencimento', models.DateTimeField(null=True, verbose_name='Data de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Cadastro Prospect')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fase', verbose_name='Fase Atual')),
            ],
            options={
                'verbose_name_plural': 'Prospects Frasson',
            },
        ),
        migrations.CreateModel(
            name='Card_Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField(null=True, verbose_name='Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fase', verbose_name='Fase')),
                ('fluxo_ambiental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_gestao_ambiental', verbose_name='Produto')),
                ('fluxo_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_gestao_credito', verbose_name='Produto')),
                ('fluxo_prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_prospects', verbose_name='Prospect')),
            ],
            options={
                'verbose_name_plural': 'Comentários Card',
            },
        ),
        migrations.CreateModel(
            name='Card_Anexos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('file', models.FileField(null=True, upload_to='pipeline/anexos', verbose_name='Arquivo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('fluxo_ambiental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_gestao_ambiental', verbose_name='Produto')),
                ('fluxo_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_gestao_credito', verbose_name='Produto')),
                ('fluxo_prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_prospects', verbose_name='Prospect')),
            ],
            options={
                'verbose_name_plural': 'Anexos Card',
            },
        ),
        migrations.CreateModel(
            name='Card_Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('ch', 'change'), ('co', 'comment'), ('cf', 'fase')], max_length=60, null=True, verbose_name='Tipo')),
                ('campo', models.CharField(max_length=60, null=True, verbose_name='Campo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Alterado por')),
                ('fluxo_ambiental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_gestao_ambiental', verbose_name='Produto')),
                ('fluxo_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_gestao_credito', verbose_name='Produto')),
                ('fluxo_prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_prospects', verbose_name='Prospect')),
            ],
            options={
                'verbose_name_plural': 'Atividades Card',
            },
        ),
        migrations.CreateModel(
            name='Phases_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('first_time_in', models.DateTimeField(null=True)),
                ('last_time_in', models.DateTimeField(null=True)),
                ('last_time_out', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fluxo_ambiental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_gestao_ambiental', verbose_name='Produto')),
                ('fluxo_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_gestao_credito', verbose_name='Produto')),
                ('fluxo_prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_prospects', verbose_name='Prospect')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Movido por')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fase', verbose_name='Fase')),
            ],
            options={
                'verbose_name_plural': 'Histórico de Fases',
            },
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao Pipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pessoas', models.ManyToManyField(related_name='pessoas_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Pessoas Autorizadas')),
            ],
            options={
                'verbose_name_plural': 'Pipe',
            },
        ),
        migrations.AddField(
            model_name='fase',
            name='pipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipe'),
        ),
    ]
