# Generated by Django 5.0 on 2024-06-11 13:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Pessoal',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('razao_social', models.CharField(max_length=255, null=True, verbose_name='Nome ou Razão Social')),
                ('natureza', models.CharField(max_length=10, null=True, verbose_name='Natureza Jurídica')),
                ('cpf_cnpj', models.CharField(max_length=30, null=True, verbose_name='CPF ou CNPJ')),
                ('numero_rg', models.CharField(max_length=50, null=True, verbose_name='Número RG')),
                ('endereco', models.CharField(max_length=255, null=True, verbose_name='Endereço')),
                ('municipio', models.CharField(max_length=255, null=True, verbose_name='Município')),
                ('uf', models.CharField(max_length=30, null=True, verbose_name='UF')),
                ('cep', models.CharField(max_length=30, null=True, verbose_name='CEP')),
                ('data_nascimento', models.DateField(null=True, verbose_name='Data Nascimento')),
                ('contato1', models.CharField(max_length=100, null=True, verbose_name='Contato 01')),
                ('contato2', models.CharField(max_length=100, null=True, verbose_name='Contato 02')),
                ('email', models.CharField(max_length=100, null=True, verbose_name='Email')),
                ('profissao', models.CharField(max_length=255, null=True, verbose_name='Profissão')),
                ('record_url', models.CharField(max_length=255, null=True, verbose_name='URL do Registro')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Cadastro Pessoal',
            },
        ),
        migrations.CreateModel(
            name='Detalhamento_Servicos',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('produto', models.CharField(max_length=255, null=True)),
                ('detalhamento_servico', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Detalhamento Serviços',
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Nome Fase')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Fases',
            },
        ),
        migrations.CreateModel(
            name='Grupos_Clientes',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_grupo', models.CharField(max_length=255, verbose_name='Nome Grupo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Grupos Clientes',
            },
        ),
        migrations.CreateModel(
            name='Instituicoes_Parceiras',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('identificacao', models.CharField(max_length=255, null=True)),
                ('record_url', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Instituições Parceiras Frasson',
            },
        ),
        migrations.CreateModel(
            name='Instituicoes_Razao_Social',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('razao_social', models.CharField(max_length=255, null=True, verbose_name='Razão Social')),
                ('cnpj', models.CharField(max_length=255, null=True, verbose_name='CNPJ')),
                ('tipo_instituicao', models.CharField(max_length=255, null=True, verbose_name='Tipo Instituição')),
                ('produto_vinculado', models.CharField(max_length=255, null=True, verbose_name='Produto Vinculado')),
                ('abreviatura', models.CharField(max_length=255, null=True, verbose_name='Abreviatura')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Instituições Razão Social',
            },
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao  Pipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Pipe',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_Pessoal_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.FileField(default='avatars/default-avatar.jpg', upload_to='avatars')),
                ('description', models.TextField(null=True, verbose_name='Descrição')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cadastro', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.cadastro_pessoal', verbose_name='Cadastro Pessoal')),
            ],
            options={
                'verbose_name_plural': 'Cad. Pessoal Informações Adicionais',
            },
        ),
        migrations.CreateModel(
            name='Contratos_Servicos',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('demais_membros', models.TextField(null=True, verbose_name='Demais Membros')),
                ('servicos_contratados', models.TextField(null=True, verbose_name='Serviços Contratados')),
                ('produto', models.CharField(max_length=255, null=True, verbose_name='Produto')),
                ('detalhes_negociacao', models.TextField(null=True, verbose_name='Detalhe Negociação')),
                ('percentual_gc', models.FloatField(null=True, verbose_name='Percentual GC')),
                ('valor_gai', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('data_assinatura', models.DateField(null=True, verbose_name='Data Assinatura')),
                ('data_vencimento', models.DateField(null=True, verbose_name='Data Vencimento')),
                ('url_record', models.CharField(max_length=255, null=True, verbose_name='URL do registro')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('contratante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.cadastro_pessoal', verbose_name='Contratante')),
            ],
            options={
                'verbose_name_plural': 'Contratos Serviços',
            },
        ),
        migrations.AddField(
            model_name='cadastro_pessoal',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.grupos_clientes', verbose_name='Id do Grupo'),
        ),
        migrations.CreateModel(
            name='Card_Produtos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('card', models.CharField(max_length=255, null=True, verbose_name='Tipo Card')),
                ('valor_operacao', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor da Operação')),
                ('faturamento_estimado', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Faturamento Estimado')),
                ('card_url', models.CharField(max_length=255, null=True, verbose_name='URL do Card')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('beneficiario', models.ManyToManyField(to='pipeline.cadastro_pessoal', verbose_name='Nome Beneficiário')),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.contratos_servicos', verbose_name='Contrato Serviço')),
                ('detalhamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.detalhamento_servicos', verbose_name='Detalhamento Serviço')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fase', verbose_name='Fase')),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.instituicoes_parceiras', verbose_name='Instituição Parceira')),
            ],
            options={
                'verbose_name_plural': 'Produtos Frasson',
            },
        ),
        migrations.AddField(
            model_name='instituicoes_parceiras',
            name='instituicao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.instituicoes_razao_social'),
        ),
        migrations.AddField(
            model_name='fase',
            name='pipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipe'),
        ),
    ]
