# Generated by Django 5.0 on 2024-06-20 17:11

import django.db.models.deletion
import pipeline.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('finances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Cobrancas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('etapa_cobranca', models.CharField(max_length=100, null=True, verbose_name='Etapa da Cobrança')),
                ('valor_operacao', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor Contratado')),
                ('percentual_contratado', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Percentual Contratado')),
                ('saldo_devedor', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Saldo Devedor')),
                ('phase_id', models.BigIntegerField(null=True, verbose_name='Id da Fase Atual')),
                ('phase_name', models.CharField(max_length=255, null=True, verbose_name='Nome da Fase Atual')),
                ('data_previsao', models.DateField(null=True, verbose_name='Data Previsão Pagamento')),
                ('valor_faturado', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor Faturado')),
                ('data_pagamento', models.DateField(null=True, verbose_name='Data Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caixa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.caixas_frasson', verbose_name='Caixa Entrada')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Cliente')),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.contratos_servicos', verbose_name='Contrato Serviço')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('detalhamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.detalhamento_servicos', verbose_name='Detalhe Demanda')),
            ],
            options={
                'verbose_name_plural': 'Cobranças Pipefy',
            },
        ),
        migrations.CreateModel(
            name='Card_Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('descricao', models.CharField(max_length=255, null=True, verbose_name='Descrição')),
                ('detalhamento', models.TextField(null=True, verbose_name='Detalhamento Pagamento')),
                ('phase_id', models.BigIntegerField(null=True, verbose_name='Id da Fase Atual')),
                ('phase_name', models.CharField(max_length=255, null=True, verbose_name='Nome da Fase Atual')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('data_vencimento', models.DateField(null=True, verbose_name='Data Vencimento')),
                ('data_pagamento', models.DateField(null=True, verbose_name='Data Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal')),
                ('caixa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.caixas_frasson', verbose_name='Caixa Saída')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.categorias_pagamentos', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pagamentos Pipefy',
            },
        ),
        migrations.CreateModel(
            name='Fase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Nome Fase')),
                ('dias_prazo', models.IntegerField(null=True)),
                ('done', models.BooleanField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('responsaveis', models.ManyToManyField(related_name='responsaveis_fase', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
            ],
            options={
                'verbose_name_plural': 'Fases',
                'ordering': ['done', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Card_Prospects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('produto', models.CharField(max_length=255, null=True, verbose_name='Produto de Interesse')),
                ('classificacao', models.CharField(max_length=255, null=True, verbose_name='Classificação do Prospect')),
                ('origem', models.CharField(max_length=255, null=True, verbose_name='Origem do Prospect')),
                ('proposta_inicial', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Proposta Inicial')),
                ('proposta_aprovada', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Proposta Aprovada')),
                ('percentual_inicial', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Percentual Inicial')),
                ('percentual_aprovado', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Percentual Aprovado')),
                ('data_vencimento', models.DateTimeField(null=True, verbose_name='Data de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Cadastro Prospect')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fase', verbose_name='Fase Atual')),
            ],
            options={
                'verbose_name_plural': 'Prospects Frasson',
            },
        ),
        migrations.CreateModel(
            name='Card_Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('card', models.CharField(max_length=255, null=True, verbose_name='Tipo Card')),
                ('prioridade', models.CharField(max_length=255, null=True, verbose_name='Prioridade')),
                ('valor_operacao', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor da Operação')),
                ('faturamento_estimado', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Faturamento Estimado')),
                ('data_vencimento', models.DateField(null=True, verbose_name='Data de Vencimento')),
                ('card_url', models.CharField(max_length=255, null=True, verbose_name='URL do Card')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.ManyToManyField(to='cadastro.cadastro_pessoal', verbose_name='Nome Beneficiário')),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.contratos_servicos', verbose_name='Contrato Serviço')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('detalhamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.detalhamento_servicos', verbose_name='Detalhamento Serviço')),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.instituicoes_parceiras', verbose_name='Instituição Parceira')),
                ('responsaveis', models.ManyToManyField(related_name='responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fase', verbose_name='Fase')),
            ],
            options={
                'verbose_name_plural': 'Produtos Frasson',
            },
        ),
        migrations.CreateModel(
            name='Phases_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('first_time_in', models.DateTimeField(null=True)),
                ('last_time_in', models.DateTimeField(null=True)),
                ('last_time_out', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cobranca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.card_cobrancas', verbose_name='Pagamento')),
                ('moved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Movido por')),
                ('pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.card_pagamentos', verbose_name='Pagamento')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fase', verbose_name='Fase')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.card_produtos', verbose_name='Produto')),
                ('prospec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.card_prospects', verbose_name='Prospect')),
            ],
            options={
                'verbose_name_plural': 'Histórico de Fases',
            },
        ),
        migrations.CreateModel(
            name='Pipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descricao Pipe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pessoas', models.ManyToManyField(related_name='pessoas_autorizadas', to=settings.AUTH_USER_MODEL, verbose_name='Pessoas Autorizadas')),
            ],
            options={
                'verbose_name_plural': 'Pipe',
            },
        ),
        migrations.AddField(
            model_name='fase',
            name='pipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipeline.pipe'),
        ),
    ]
