# Generated by Django 5.0 on 2024-06-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='done',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
