# Generated by Django 5.0 on 2024-06-27 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_Coments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField(null=True, verbose_name='Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('card_cobranca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.card_cobrancas', verbose_name='Card Cobranças')),
                ('card_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.card_pagamentos', verbose_name='Card Pagamentos')),
                ('card_produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.card_produtos', verbose_name='Card Produtos')),
                ('card_prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.card_prospects', verbose_name='Card Prospects')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name_plural': 'Produtos Frasson',
            },
        ),
    ]
