# Generated by Django 5.0 on 2024-07-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_fluxo_gestao_credito_valor_operacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxo_gestao_credito',
            name='card',
            field=models.CharField(max_length=255, null=True, verbose_name='Tipo Card'),
        ),
    ]
