# Generated by Django 5.0 on 2024-06-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_fase_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fase',
            name='done',
            field=models.BooleanField(null=True),
        ),
    ]
