# Generated by Django 5.0 on 2024-07-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_fluxo_gestao_credito_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card_anexos',
            old_name='updated_by',
            new_name='uploaded_by',
        ),
    ]
