# Generated by Django 5.0 on 2024-06-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_card_produtos_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_produtos',
            name='code',
            field=models.BigIntegerField(default=518654590, unique=True),
        ),
    ]
