# Generated by Django 5.0 on 2024-07-02 11:34

import django.db.models.deletion
import pipeline.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_initial'),
        ('pipeline', '0004_rename_updated_by_card_anexos_uploaded_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card_anexos',
            name='pvtec_response',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='card_anexos',
            name='file',
            field=models.FileField(null=True, upload_to=pipeline.models.upload_anexo, verbose_name='Arquivo'),
        ),
        migrations.CreateModel(
            name='PVTEC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('data_vencimento', models.DateTimeField(null=True, verbose_name='Data de Vencimento')),
                ('atividade', models.CharField(choices=[('AC', 'Ação com Cliente'), ('AT', 'Ação com Terceiros'), ('ET', 'Entrega Técnica'), ('LLC', 'LITEC - Levantamento de Campo'), ('LPT', 'LITEC - PTC'), ('LNT', 'LITEC - NT'), ('FB', 'Feedback'), ('RC', 'Renovação de Contrato'), ('ND', 'Novas Demandas'), ('MT', 'Make Time'), ('FOC', 'Formalização Operação de Crédito'), ('OF', 'Outras Frentes')], max_length=5, null=True, verbose_name='Atividade')),
                ('orientacoes', models.TextField(null=True, verbose_name='Orientações')),
                ('status', models.CharField(choices=[('EA', 'Em Andamento'), ('OK', 'Concluído')], default='EA', max_length=3, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Cadastro Prospect')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('detalhe_demanda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.detalhamento_servicos', verbose_name='Detalhe Demanda')),
                ('fluxo_ambiental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_gestao_ambiental', verbose_name='Produto')),
                ('fluxo_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_gestao_credito', verbose_name='Produto')),
                ('phase_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fase', verbose_name='Fase Origem')),
                ('responsaveis', models.ManyToManyField(related_name='responsaveis_pvtec', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis')),
            ],
            options={
                'verbose_name_plural': 'PVTEC',
            },
        ),
        migrations.CreateModel(
            name='Card_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('text', models.TextField(null=True, verbose_name='Texto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('fluxo_ambiental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_gestao_ambiental', verbose_name='Produto')),
                ('fluxo_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_gestao_credito', verbose_name='Produto')),
                ('fluxo_prospect', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_prospects', verbose_name='Prospect')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fase', verbose_name='Fase')),
                ('pvtec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.pvtec', verbose_name='PVTEC')),
            ],
            options={
                'verbose_name_plural': 'Comentários Card',
            },
        ),
        migrations.AddField(
            model_name='card_anexos',
            name='pvtec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.pvtec', verbose_name='Produto'),
        ),
        migrations.DeleteModel(
            name='Card_Coments',
        ),
    ]
