# Generated by Django 5.0 on 2024-07-02 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_initial'),
        ('pipeline', '0006_card_anexos_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_activities',
            name='campo',
            field=models.TextField(null=True, verbose_name='Campo'),
        ),
        migrations.AlterField(
            model_name='pvtec',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pvtec',
            name='fluxo_ambiental',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_gestao_ambiental', verbose_name='Fluxo Ambiental'),
        ),
        migrations.AlterField(
            model_name='pvtec',
            name='fluxo_credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fluxo_gestao_credito', verbose_name='Fluxo Crédito'),
        ),
    ]
