# Generated by Django 5.0 on 2024-06-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0006_alter_card_produtos_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_produtos',
            name='code',
            field=models.BigIntegerField(unique=True),
        ),
    ]
