# Generated by Django 5.0 on 2024-06-17 16:03

import django.db.models.deletion
import pipeline.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0007_alter_card_produtos_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipe',
            name='code',
            field=models.BigIntegerField(default=pipeline.models.gerarcode, unique=True),
        ),
        migrations.AlterField(
            model_name='card_produtos',
            name='code',
            field=models.BigIntegerField(default=pipeline.models.gerarcode, unique=True),
        ),
        migrations.CreateModel(
            name='Card_Prospects',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('produto', models.CharField(max_length=255, null=True, verbose_name='Produto de Interesse')),
                ('classificacao', models.CharField(max_length=255, null=True, verbose_name='Classificação do Prospect')),
                ('origem', models.CharField(max_length=255, null=True, verbose_name='Origem do Prospect')),
                ('proposta_inicial', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Proposta Inicial')),
                ('proposta_aprovada', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Proposta Aprovada')),
                ('percentual_inicial', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Percentual Inicial')),
                ('percentual_aprovado', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Percentual Aprovado')),
                ('data_vencimento', models.DateTimeField(null=True, verbose_name='Data de Vencimento')),
                ('card_url', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.cadastro_pessoal', verbose_name='Cadastro Prospect')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.fase', verbose_name='Fase Atual')),
            ],
            options={
                'verbose_name_plural': 'Prospects Frasson',
            },
        ),
    ]
