# Generated by Django 5.0 on 2024-06-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_pipe_code_alter_card_produtos_code_card_prospects'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_produtos',
            name='data_vencimento',
            field=models.DateTimeField(null=True, verbose_name='Data de Vencimento'),
        ),
    ]
