# Generated by Django 5.0 on 2024-07-05 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0008_remove_pvtec_cliente_remove_pvtec_detalhe_demanda'),
    ]

    operations = [
        migrations.AddField(
            model_name='fase',
            name='destinos_permitidos',
            field=models.ManyToManyField(blank=True, related_name='fases_origem', to='pipeline.fase'),
        ),
    ]
