# Generated by Django 5.0 on 2024-07-08 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_fase_destinos_permitidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_activities',
            name='pvtec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.pvtec', verbose_name='PVTEC'),
        ),
    ]
