# Generated by Django 5.0 on 2024-06-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0009_card_produtos_data_vencimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Produtos',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('acronym', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sigla')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cadastro Produtos',
            },
        ),
        migrations.AddField(
            model_name='card_produtos',
            name='prioridade',
            field=models.CharField(max_length=255, null=True, verbose_name='Prioridade'),
        ),
    ]
