# Generated by Django 5.0 on 2024-06-18 11:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0010_cadastro_produtos_card_produtos_prioridade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='card_produtos',
            name='responsaveis',
            field=models.ManyToManyField(related_name='responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Nome Beneficiário'),
        ),
    ]
