# Generated by Django 5.0 on 2024-06-18 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0011_card_produtos_responsaveis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_produtos',
            name='data_vencimento',
            field=models.DateField(null=True, verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='card_produtos',
            name='responsaveis',
            field=models.ManyToManyField(related_name='responsaveis', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
    ]
