# Generated by Django 5.0 on 2024-08-05 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0012_alter_fluxo_prospects_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxo_prospects',
            name='responsaveis',
            field=models.ManyToManyField(related_name='responsaveisprospect', to=settings.AUTH_USER_MODEL, verbose_name='Responsáveis'),
        ),
    ]
