# Generated by Django 5.0 on 2024-08-09 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_activities_cobranca_activities_pagamento_and_more'),
        ('pipeline', '0013_fluxo_prospects_responsaveis'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_comments',
            name='cobranca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.cobrancas', verbose_name='Cobrança'),
        ),
        migrations.AddField(
            model_name='card_comments',
            name='pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.pagamentos', verbose_name='Pagamento'),
        ),
    ]
