# Generated by Django 5.0 on 2024-09-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0014_card_comments_cobranca_card_comments_pagamento'),
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atualizacoes_acompanhamento_gai',
            name='processo',
        ),
        migrations.RemoveField(
            model_name='atualizacoes_acompanhamento_gai',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='atualizacoes_acompanhamento_gai',
            name='status',
        ),
        migrations.AddField(
            model_name='card_anexos',
            name='acomp_gai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.acompanhamento_processos', verbose_name='Produto'),
        ),
        migrations.DeleteModel(
            name='Acompanhamento_GAI',
        ),
        migrations.DeleteModel(
            name='Atualizacoes_Acompanhamento_GAI',
        ),
        migrations.DeleteModel(
            name='Status_Acompanhamento',
        ),
    ]
