# Generated by Django 5.0 on 2024-09-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0015_remove_atualizacoes_acompanhamento_gai_processo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fluxo_prospects',
            name='cliente',
        ),
        migrations.AddField(
            model_name='fluxo_prospects',
            name='nome',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome Prospect'),
        ),
    ]
