# Generated by Django 5.0 on 2024-09-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0018_fluxo_prospects_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxo_prospects',
            name='prioridade',
            field=models.CharField(choices=[('A', 'Alta'), ('M', 'Média'), ('B', 'Baixa')], max_length=2, null=True, verbose_name='Prioridade'),
        ),
    ]
