# Generated by Django 5.0 on 2024-09-16 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0020_analisetecnica'),
        ('processes', '0002_rename_user_acompanhamento_processos_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_anexos',
            name='analise_tecnica',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.analisetecnica', verbose_name='AT'),
        ),
        migrations.AlterField(
            model_name='card_anexos',
            name='acomp_gai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.acompanhamento_processos', verbose_name='Acomp GAI'),
        ),
        migrations.AlterField(
            model_name='card_anexos',
            name='pvtec',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeline.pvtec', verbose_name='PVTEC'),
        ),
    ]
