# Generated by Django 5.0 on 2024-09-17 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0020_remove_contratos_ambiental_prospect_and_more'),
        ('pipeline', '0021_card_anexos_analise_tecnica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluxo_prospects',
            name='contrato_gai',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.contratos_ambiental', verbose_name='Contrato GAI'),
        ),
        migrations.AddField(
            model_name='fluxo_prospects',
            name='contrato_gc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.contratos_credito', verbose_name='Contrato GC'),
        ),
    ]
