# Generated by Django 5.0 on 2024-10-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0022_fluxo_prospects_contrato_gai_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fase',
            options={'verbose_name_plural': 'Fases'},
        ),
    ]
