# Generated by Django 5.0 on 2024-07-01 10:48

import django.db.models.deletion
import pipeline.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ver_menu_financeiro', 'Ver Menu Financeiro'), ('ver_saldos_bancarios', 'Ver Saldos Bancários'), ('ver_dre_consolidado', 'Ver DRE Consolidado'), ('ver_dre_provisionado', 'Ver DRE Provisionado')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipo_Receita_Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=1, null=True, verbose_name='Receita ou Despesa')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descrição da Receita ou Despesa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Receita ou Despesa',
            },
        ),
        migrations.CreateModel(
            name='Caixas_Frasson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=255, null=True, verbose_name='Nome Caixa')),
                ('sigla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla')),
                ('numero_agencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Agência')),
                ('numero_conta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Conta')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo', models.FileField(null=True, upload_to='logos/caixas', verbose_name='Logo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Caixas Frasson',
            },
        ),
        migrations.CreateModel(
            name='Categorias_Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('category', models.CharField(max_length=255, verbose_name='Descrição da categoria')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Descrição da sub categoria')),
                ('classification', models.CharField(choices=[('COE', 'Custo Operacional'), ('DOP', 'Despesa Operacional'), ('DNOP', 'Despesa Não Operacional'), ('II', 'Impostos Indiretos'), ('ID', 'Impostos Diretos'), ('RS', 'Retirada de Sócio'), ('PC', 'Pagamento Comissão'), ('AI', 'Ativos Imobilizados'), ('O', 'Outros')], max_length=5, null=True, verbose_name='Classificação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Categorias Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Contratos_Ambiental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('detalhes', models.TextField(null=True, verbose_name='Detalhe Negociação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('data_assinatura', models.DateField(null=True, verbose_name='Data Assinatura')),
                ('data_vencimento', models.DateField(null=True, verbose_name='Data Vencimento')),
                ('pdf', models.FileField(null=True, upload_to='finances/contratos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contratante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Contratante')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servicos', models.ManyToManyField(to='cadastro.detalhamento_servicos', verbose_name='Serviços Contratados')),
            ],
            options={
                'verbose_name_plural': 'Contratos Ambiental',
            },
        ),
        migrations.CreateModel(
            name='Contratos_Ambiental_Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('etapa', models.CharField(choices=[('A', 'Assinatura Contrato'), ('P', 'Protocolo'), ('E', 'Encerramento')], max_length=1, null=True, verbose_name='Etapa Pagamento')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='percentual')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.contratos_ambiental')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.detalhamento_servicos')),
            ],
            options={
                'verbose_name_plural': 'Contratos Ambiental - Forma Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Contratos_Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('detalhes', models.TextField(null=True, verbose_name='Detalhe Negociação')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('data_assinatura', models.DateField(null=True, verbose_name='Data Assinatura')),
                ('data_vencimento', models.DateField(null=True, verbose_name='Data Vencimento')),
                ('pdf', models.FileField(null=True, upload_to='finances/contratos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contratante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Contratante')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servicos', models.ManyToManyField(to='cadastro.detalhamento_servicos', verbose_name='Serviços Contratados')),
            ],
            options={
                'verbose_name_plural': 'Contratos Crédito',
            },
        ),
        migrations.CreateModel(
            name='Cobrancas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('etapa_cobranca', models.CharField(max_length=100, null=True, verbose_name='Etapa da Cobrança')),
                ('valor_operacao', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor Contratado')),
                ('percentual_contratado', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Percentual Contratado')),
                ('saldo_devedor', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Saldo Devedor')),
                ('status', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=10, null=True, verbose_name='Status')),
                ('data_previsao', models.DateField(null=True, verbose_name='Data Previsão Pagamento')),
                ('valor_faturado', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor Faturado')),
                ('data_pagamento', models.DateField(null=True, verbose_name='Data Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caixa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.caixas_frasson', verbose_name='Caixa Entrada')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('detalhamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.detalhamento_servicos', verbose_name='Detalhe Demanda')),
                ('contrato_ambiental', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.contratos_ambiental', verbose_name='Contrato Serviço')),
                ('contrato_credito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.contratos_credito', verbose_name='Contrato Serviço')),
            ],
            options={
                'verbose_name_plural': 'Cobranças Pipefy',
            },
        ),
        migrations.CreateModel(
            name='Contratos_Credito_Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('etapa', models.CharField(default='Encerramento', max_length=20, null=True, verbose_name='Etapa Pagamento')),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=8, null=True, verbose_name='percentual')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.contratos_ambiental')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('servico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.detalhamento_servicos')),
            ],
            options={
                'verbose_name_plural': 'Contratos Crédito - Forma Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Lancamentos_Automaticos_Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Lançamento')),
                ('detalhamento', models.TextField(blank=True, null=True, verbose_name='Detalhamento do Lançamento')),
                ('valor_pagamento', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Pagamento')),
                ('dia_vencimento', models.IntegerField(blank=True, null=True, verbose_name='Dia do Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Beneficiário')),
                ('categoria_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.categorias_pagamentos')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Lançamentos Autom. Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.BigIntegerField(default=pipeline.models.gerarcode, unique=True)),
                ('descricao', models.CharField(max_length=255, null=True, verbose_name='Descrição')),
                ('detalhamento', models.TextField(null=True, verbose_name='Detalhamento Pagamento')),
                ('status', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=10, null=True, verbose_name='Status')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('data_vencimento', models.DateField(null=True, verbose_name='Data Vencimento')),
                ('data_pagamento', models.DateField(null=True, verbose_name='Data Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal')),
                ('caixa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.caixas_frasson', verbose_name='Caixa Saída')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.categorias_pagamentos', verbose_name='Categoria')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pagamentos Pipefy',
            },
        ),
        migrations.CreateModel(
            name='Reembolso_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField(null=True, verbose_name='Data')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor')),
                ('cobranca', models.BooleanField(default=False, verbose_name='Cobrança?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reembolsos Clientes',
            },
        ),
        migrations.CreateModel(
            name='Resultados_Financeiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('data', models.DateField(null=True, verbose_name='Data da Movimentação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor da Movimentação')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descrição da Movimentação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caixa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.caixas_frasson', verbose_name='Caixa')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.tipo_receita_despesa', verbose_name='Tipo de Receita ou Despesa')),
            ],
            options={
                'verbose_name_plural': 'Movimentações Financeiras',
            },
        ),
        migrations.CreateModel(
            name='Transferencias_Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caixa_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixa_destino_id', to='finances.caixas_frasson')),
                ('caixa_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixa_origem_id', to='finances.caixas_frasson')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transferências Entre Contas',
            },
        ),
    ]
