# Generated by Django 5.0 on 2024-04-23 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipefy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ver_menu_financeiro', 'Ver Menu Financeiro'), ('ver_saldos_bancarios', 'Ver Saldos Bancários'), ('ver_dre_consolidado', 'Ver DRE Consolidado'), ('ver_dre_provisionado', 'Ver DRE Provisionado')],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caixas_Frasson',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('caixa', models.CharField(max_length=255, null=True, verbose_name='Conta')),
                ('sigla', models.CharField(blank=True, max_length=50, null=True, verbose_name='Sigla')),
                ('numero_agencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Agência')),
                ('numero_conta', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número Conta')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Caixas Frasson',
            },
        ),
        migrations.CreateModel(
            name='Categorias_Pagamentos',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=255, verbose_name='Descrição da categoria')),
                ('sub_category', models.CharField(max_length=255, verbose_name='Descrição da sub categoria')),
                ('classification', models.CharField(max_length=255, verbose_name='Classificação')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias Pagamentos',
            },
        ),
        migrations.CreateModel(
            name='Cobrancas_Pipefy',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('etapa_cobranca', models.CharField(max_length=100, null=True, verbose_name='Etapa da Cobrança')),
                ('valor_operacao', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor Contratado')),
                ('percentual_contratado', models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Percentual Contratado')),
                ('saldo_devedor', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Saldo Devedor')),
                ('data_previsao', models.DateField(null=True, verbose_name='Data Previsão Pagamento')),
                ('valor_faturado', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor Faturado')),
                ('data_pagamento', models.DateField(null=True, verbose_name='Data Pagamento')),
                ('card_url', models.CharField(max_length=255, null=True, verbose_name='URL do card')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('caixa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.caixas_frasson', verbose_name='Caixa Entrada')),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipefy.cadastro_pessoal', verbose_name='Cliente')),
                ('contrato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipefy.contratos_servicos', verbose_name='Contrato Serviço')),
                ('detalhamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipefy.detalhamento_servicos', verbose_name='Detalhe Demanda')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipefy.fase', verbose_name='Fase')),
            ],
            options={
                'verbose_name_plural': 'Cobranças Pipefy',
            },
        ),
        migrations.CreateModel(
            name='Pagamentos_Pipefy',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255, null=True, verbose_name='Descrição')),
                ('detalhamento', models.TextField(null=True, verbose_name='Detalhamento Pagamento')),
                ('valor_pagamento', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('data_vencimento', models.DateField(null=True, verbose_name='Data Vencimento')),
                ('data_pagamento', models.DateField(null=True, verbose_name='Data Pagamento')),
                ('card_url', models.CharField(max_length=255, null=True, verbose_name='URL do card')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipefy.fornecedores_colaboradores')),
                ('caixa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.caixas_frasson', verbose_name='Caixa Saída')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.categorias_pagamentos', verbose_name='Categoria')),
                ('phase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pipefy.fase', verbose_name='Fase')),
            ],
            options={
                'verbose_name_plural': 'Pagamentos Pipefy',
            },
        ),
    ]
