# Generated by Django 5.0 on 2024-05-07 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobrancas_pipefy',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='pagamentos_pipefy',
            name='phase',
        ),
        migrations.AddField(
            model_name='cobrancas_pipefy',
            name='phase_id',
            field=models.BigIntegerField(null=True, verbose_name='Id da Fase Atual'),
        ),
        migrations.AddField(
            model_name='cobrancas_pipefy',
            name='phase_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome da Fase Atual'),
        ),
        migrations.AddField(
            model_name='pagamentos_pipefy',
            name='phase_id',
            field=models.BigIntegerField(null=True, verbose_name='Id da Fase Atual'),
        ),
        migrations.AddField(
            model_name='pagamentos_pipefy',
            name='phase_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome da Fase Atual'),
        ),
    ]
