# Generated by Django 5.0 on 2024-07-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos_ambiental',
            name='data_assinatura',
            field=models.DateField(blank=True, null=True, verbose_name='Data Assinatura'),
        ),
        migrations.AlterField(
            model_name='contratos_ambiental',
            name='data_vencimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data Vencimento'),
        ),
        migrations.AlterField(
            model_name='contratos_ambiental',
            name='detalhes',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhe Negociação'),
        ),
        migrations.AlterField(
            model_name='contratos_ambiental',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='finances/contratos', verbose_name='PDF Contrato'),
        ),
    ]
