# Generated by Django 5.0 on 2024-05-21 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_remove_cobrancas_pipefy_phase_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Receita_Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('R', 'Receita'), ('D', 'Despesa')], max_length=1, null=True, verbose_name='Receita ou Despesa')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descrição da Receita ou Despesa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tipos de Receita ou Despesa',
            },
        ),
        migrations.CreateModel(
            name='Reembolso_Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('data', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caixa_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.caixas_frasson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reembolsos Clientes',
            },
        ),
        migrations.CreateModel(
            name='Resultados_Financeiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True, verbose_name='Data da Movimentação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor da Movimentação')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descrição da Movimentação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caixa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.caixas_frasson', verbose_name='Caixa')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tipo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.tipo_receita_despesa', verbose_name='Tipo de Receita ou Despesa')),
            ],
            options={
                'verbose_name_plural': 'Movimentações Financeiras',
            },
        ),
        migrations.CreateModel(
            name='Transferencias_Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('data', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caixa_destino', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixa_destino_id', to='finances.caixas_frasson')),
                ('caixa_origem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixa_origem_id', to='finances.caixas_frasson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Transferências Entre Contas',
            },
        ),
    ]
