# Generated by Django 5.0 on 2024-07-10 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_activities_anexos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos_ambiental_pagamentos',
            name='observacoes',
        ),
        migrations.RemoveField(
            model_name='contratos_credito_pagamentos',
            name='observacoes',
        ),
    ]
