# Generated by Django 5.0 on 2024-05-21 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0003_tipo_receita_despesa_reembolso_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Status do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Status Pagamento',
            },
        ),
        migrations.CreateModel(
            name='Saldos_Iniciais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('data_referencia', models.DateField(null=True, verbose_name='Data Referência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caixa', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.caixas_frasson', verbose_name='Caixa')),
            ],
            options={
                'verbose_name_plural': 'Saldos Iniciais',
            },
        ),
    ]
