# Generated by Django 5.0 on 2024-07-11 10:20

import finances.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_remove_contratos_ambiental_pagamentos_observacoes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos_ambiental',
            name='data_vencimento',
        ),
        migrations.AddField(
            model_name='contratos_ambiental',
            name='code',
            field=models.BigIntegerField(default=finances.models.gerarcode, unique=True),
        ),
        migrations.AddField(
            model_name='contratos_credito',
            name='code',
            field=models.BigIntegerField(default=finances.models.gerarcode, unique=True),
        ),
        migrations.AlterField(
            model_name='cobrancas',
            name='code',
            field=models.BigIntegerField(default=finances.models.gerarcode, unique=True),
        ),
        migrations.AlterField(
            model_name='pagamentos',
            name='code',
            field=models.BigIntegerField(default=finances.models.gerarcode, unique=True),
        ),
    ]
