# Generated by Django 5.0 on 2024-05-22 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_status_pagamentos_saldos_iniciais'),
        ('pipefy', '0007_remove_card_prospects_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancamentos_Automaticos_Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição do Lançamento')),
                ('detalhamento', models.TextField(blank=True, null=True, verbose_name='Detalhamento do Lançamento')),
                ('valor_pagamento', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Pagamento')),
                ('dia_vencimento', models.IntegerField(blank=True, null=True, verbose_name='Dia do Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipefy.fornecedores_colaboradores', verbose_name='Beneficiário')),
                ('categoria_pagamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.categorias_pagamentos')),
            ],
            options={
                'verbose_name_plural': 'Lançamentos Autom. Pagamentos',
            },
        ),
    ]
