# Generated by Django 5.0 on 2024-07-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_remove_cobrancas_contrato_ambiental_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobrancas',
            options={'verbose_name_plural': 'Cobranças'},
        ),
        migrations.AlterField(
            model_name='activities',
            name='type',
            field=models.CharField(choices=[('cr', 'criou'), ('ch', 'change'), ('c', 'concluiu')], max_length=60, null=True, verbose_name='Tipo'),
        ),
    ]
