# Generated by Django 5.0 on 2024-07-17 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_categoria_cadastro_options_and_more'),
        ('finances', '0008_alter_cobrancas_status_alter_pagamentos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancas',
            name='detalhamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.detalhamento_servicos', verbose_name='Detalhamento'),
        ),
    ]
