# Generated by Django 5.0 on 2024-07-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_cobrancas_detalhamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos_credito',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor'),
        ),
    ]
