# Generated by Django 5.0 on 2024-08-05 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_contratos_credito_valor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagamentos',
            options={'verbose_name_plural': 'Pagamentos'},
        ),
    ]
