# Generated by Django 5.0 on 2024-08-09 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_alter_pagamentos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='cobranca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.cobrancas', verbose_name='Cobrança'),
        ),
        migrations.AddField(
            model_name='activities',
            name='pagamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.pagamentos', verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='activities',
            name='type',
            field=models.CharField(choices=[('cr', 'criou'), ('co', 'comment'), ('ch', 'change'), ('c', 'concluiu')], max_length=60, null=True, verbose_name='Tipo'),
        ),
    ]
