# Generated by Django 5.0 on 2024-08-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_activities_cobranca_activities_pagamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentos',
            name='observacoes',
            field=models.TextField(null=True, verbose_name='Observações'),
        ),
    ]
