# Generated by Django 5.0 on 2024-09-12 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0014_alter_contratos_ambiental_pagamentos_etapa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrancas',
            name='etapa_ambiental',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.contratos_ambiental_pagamentos', verbose_name='Etapa da Cobrança GAI'),
        ),
        migrations.AlterField(
            model_name='cobrancas',
            name='etapa_credito',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.contratos_credito_pagamentos', verbose_name='Etapa da Cobrança GC'),
        ),
    ]
