# Generated by Django 5.0 on 2024-09-16 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_alter_cobrancas_etapa_ambiental_and_more'),
        ('pipeline', '0021_card_anexos_analise_tecnica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos_ambiental',
            name='pdf',
        ),
        migrations.RemoveField(
            model_name='contratos_credito',
            name='pdf',
        ),
        migrations.AddField(
            model_name='contratos_ambiental',
            name='prospect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.fluxo_prospects', verbose_name='Contratante'),
        ),
    ]
