# Generated by Django 5.0 on 2024-09-16 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0016_remove_contratos_ambiental_pdf_and_more'),
        ('pipeline', '0021_card_anexos_analise_tecnica_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos_credito',
            name='prospect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.fluxo_prospects', verbose_name='Contratante'),
        ),
        migrations.AlterField(
            model_name='contratos_credito_pagamentos',
            name='etapa',
            field=models.CharField(default='Encerramento', max_length=50, null=True, verbose_name='Etapa Pagamento'),
        ),
    ]
