# Generated by Django 5.0 on 2024-09-16 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0017_contratos_credito_prospect_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos_credito',
            name='percentual',
        ),
    ]
