# Generated by Django 5.0 on 2024-09-16 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0018_remove_contratos_credito_percentual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos_credito_pagamentos',
            name='contrato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.contratos_credito'),
        ),
    ]
