# Generated by Django 5.0 on 2024-09-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0019_alter_contratos_credito_pagamentos_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contratos_ambiental',
            name='prospect',
        ),
        migrations.RemoveField(
            model_name='contratos_credito',
            name='prospect',
        ),
    ]
