# Generated by Django 5.0 on 2024-07-01 10:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricantes_Bombas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_fabricante', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fabricantes Bombas',
            },
        ),
        migrations.CreateModel(
            name='Fabricantes_Pivots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome_fabricante', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Fabricantes Pivots',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_Pivots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('propriedade_localizacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Fazenda')),
                ('identificacao_pivot', models.CharField(blank=True, max_length=100, null=True, verbose_name='Indentificação do Pivot')),
                ('area_circular_ha', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Área circular (ha)')),
                ('vazao_total_m3_h', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Vazão Total (m3/h)')),
                ('lamina_bruta_21_h', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Lâmina Bruta (mm/dia)')),
                ('periodo_rele_100', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Período giro 100% (h)')),
                ('raio_irrigado_m', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Raio irrigado (m)')),
                ('lat_center_gd', models.DecimalField(decimal_places=8, max_digits=10, null=True, verbose_name='Lat. Centro GD')),
                ('long_center_gd', models.DecimalField(decimal_places=8, max_digits=10, null=True, verbose_name='Long. Centro GD')),
                ('comprimento_adutora_m', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Comprimento Adutora (m)')),
                ('diametro_adutora_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Diâmetro Adutora (mm)')),
                ('modelo_bomba', models.CharField(blank=True, max_length=255, null=True, verbose_name='Modelo Bomba')),
                ('fabricante_motor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Marca Motor')),
                ('pot_motor_cv', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Pot. Motor (cv)')),
                ('data_montagem_pivot', models.DateField(blank=True, null=True, verbose_name='Data Montagem Pivot')),
                ('file', models.FileField(default=None, null=True, upload_to='pivots/fichas', verbose_name='Ficha Técnica PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('municipio_localizacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.municipios', verbose_name='Município Localização')),
                ('proprietario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Proprietário')),
                ('fabricante_bomba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='irrigation.fabricantes_bombas', verbose_name='Fabricante Bomba')),
                ('fabricante_pivot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='irrigation.fabricantes_pivots', verbose_name='Fabricante Pivot')),
            ],
            options={
                'verbose_name_plural': 'Cadastro Pivots',
            },
        ),
    ]
