# Generated by Django 5.0 on 2024-07-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro_pivots',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='cadastro_pivots',
            name='cpf_cnpj_proprietario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CPF/CNPJ Proprietário'),
        ),
        migrations.AddField(
            model_name='cadastro_pivots',
            name='razao_social_proprietario',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Razão Social Proprietário'),
        ),
    ]
