# Generated by Django 5.0 on 2024-05-29 16:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications_Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Título da Mensagem')),
                ('subject', models.CharField(max_length=255, null=True, verbose_name='Assunto da Mensagem')),
                ('text', models.TextField(null=True, verbose_name='Texto da Mensagem')),
                ('icon', models.CharField(max_length=100, null=True, verbose_name='Icone da Mensagem')),
                ('icon_color', models.CharField(max_length=30, null=True, verbose_name='Cor do Ícone')),
                ('read', models.BooleanField(default=False, null=True, verbose_name='Mensagem Lida')),
                ('archived', models.BooleanField(default=False, null=True, verbose_name='Mensagem Arquivada')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Arquivada em')),
                ('deleted', models.BooleanField(default=False, null=True, verbose_name='Mensagem Deletada')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Enviada para a lixeira em')),
                ('starred', models.BooleanField(default=False, null=True, verbose_name='Mensagem Favoritada')),
                ('starred_at', models.DateTimeField(blank=True, null=True, verbose_name='Favoritada em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipient_id', to=settings.AUTH_USER_MODEL, verbose_name='Destinatário da Mensagem')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender_id', to=settings.AUTH_USER_MODEL, verbose_name='Remetente da Mensagem')),
            ],
            options={
                'verbose_name_plural': 'Mensagens de Notificação',
            },
        ),
    ]
