# Generated by Django 5.0 on 2024-06-20 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessos_Bancarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('agencia', models.CharField(max_length=20, null=True, verbose_name='Número Agência')),
                ('conta', models.CharField(max_length=20, null=True, verbose_name='Número Conta')),
                ('usuario', models.CharField(max_length=30, null=True, verbose_name='Usuário')),
                ('chave_jota', models.CharField(max_length=30, null=True, verbose_name='Chave J')),
                ('senha_acesso', models.CharField(max_length=50, null=True, verbose_name='Senha de Acesso')),
                ('senha_conta', models.CharField(max_length=15, null=True, verbose_name='Senha da Conta')),
                ('contato_instituicao', models.CharField(max_length=200, null=True, verbose_name='Contato Instituição')),
                ('telefone_contato', models.CharField(max_length=20, null=True, verbose_name='Telefone Contato')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.instituicoes_razao_social', verbose_name='Instituição')),
            ],
            options={
                'verbose_name_plural': 'Acessos Bancários',
            },
        ),
    ]
