# Generated by Django 5.0 on 2024-07-01 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pipeline', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Acompanhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, null=True, verbose_name='Descrição do Status')),
                ('sigla', models.CharField(max_length=255, null=True, verbose_name='Sigla Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Status Processos GAI',
            },
        ),
        migrations.CreateModel(
            name='Processos_Andamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requerimento', models.CharField(max_length=255, null=True, verbose_name='Número do Requerimento')),
                ('data_requerimento', models.DateField(null=True, verbose_name='Data Requerimento')),
                ('data_enquadramento', models.DateField(null=True, verbose_name='Data Enquadramento')),
                ('data_validacao', models.DateField(null=True, verbose_name='Data Validação Prévia')),
                ('valor_boleto', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Valor do Boleto')),
                ('vencimento_boleto', models.DateField(null=True, verbose_name='Data Vencimento Boleto')),
                ('data_formacao', models.DateField(null=True, verbose_name='Data Formação do Processo')),
                ('numero_processo', models.CharField(max_length=255, null=True, verbose_name='Número do Processo')),
                ('processo_sei', models.CharField(max_length=255, null=True, verbose_name='Número do Processo SEI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pipeline.fluxo_gestao_ambiental', verbose_name='Processo Frason')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Processos Gestão Ambiental',
            },
        ),
        migrations.CreateModel(
            name='Acompanhamento_Processos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(null=True, verbose_name='Data da atualização')),
                ('detalhamento', models.TextField(null=True, verbose_name='Detalhamento da Atualização')),
                ('proxima_consulta', models.DateField(null=True, verbose_name='Próxima Consulta')),
                ('file', models.FileField(blank=True, default=None, null=True, upload_to='inema/followup', verbose_name='Arquivo PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('processo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='processes.processos_andamento', verbose_name='Processo')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='processes.status_acompanhamento', verbose_name='Status Processos')),
            ],
            options={
                'verbose_name_plural': 'Registros de Acompanhamento',
            },
        ),
    ]
