# Generated by Django 5.0 on 2024-09-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acompanhamento_processos',
            old_name='user',
            new_name='created_by',
        ),
    ]
