# Generated by Django 5.0 on 2024-06-20 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Licencas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('detalhe_licenca', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detalhe da Licença')),
                ('numero_requerimento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Número do Requerimento')),
                ('numero_processo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Número do Processo')),
                ('numero_licenca', models.CharField(blank=True, max_length=150, null=True, verbose_name='Número da Licença')),
                ('area_beneficiada', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='Área Beneficiada')),
                ('data_emissao', models.DateField(blank=True, null=True, verbose_name='Data Emissão')),
                ('data_validade', models.DateField(blank=True, null=True, verbose_name='Data Validade')),
                ('dias_renovacao', models.IntegerField(default=90, null=True, verbose_name='Prazo Renovação (dias)')),
                ('descricao', models.TextField(null=True, verbose_name='Descrição da Licença')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('beneficiario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Beneficiário')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.instituicoes_razao_social', verbose_name='Instituição')),
                ('propriedades', models.ManyToManyField(to='farms.imoveis_rurais', verbose_name='Imóveis Rurais')),
                ('tipo_licenca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.detalhamento_servicos', verbose_name='Tipo Licença')),
            ],
            options={
                'verbose_name_plural': 'Cadastro Licenças',
            },
        ),
    ]
