# Generated by Django 5.0 on 2024-03-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_allowed_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowed_emails',
            name='email',
            field=models.CharField(error_messages={'unique': 'E-Mail já está autorizado!'}, max_length=150, null=True, unique=True, verbose_name='Email'),
        ),
    ]
