# Generated by Django 5.0 on 2024-03-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_allowed_emails_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('ver_menu_operacional', 'Ver Menu Operacional'), ('ver_menu_credito', 'Ver Menu Crédito Rural'), ('ver_menu_ambiental', 'Ver Menu Ambiental')],
                'managed': False,
            },
        ),
    ]
