# Generated by Django 5.0 on 2024-06-20 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro_Ambiental_Rural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('numero_car', models.CharField(blank=True, max_length=150, null=True, verbose_name='Número do CAR')),
                ('area_preservacao_permanente', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Área APP')),
                ('area_uso_restrito', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Área Uso Restrito')),
                ('condicao_cadastro', models.CharField(blank=True, max_length=250, null=True, verbose_name='Condição Cadastro')),
                ('area_imovel', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Área Imóvel')),
                ('modulos_fiscais', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Módulos Fiscais')),
                ('endereco_municipio', models.CharField(blank=True, max_length=250, null=True, verbose_name='Endereço Município')),
                ('endereco_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('endereco_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Longitude')),
                ('data_registro', models.DateField(blank=True, null=True, verbose_name='Data Registro')),
                ('data_analise', models.DateField(blank=True, null=True, verbose_name='Data Análise')),
                ('data_retificacao', models.DateField(blank=True, null=True, verbose_name='Data Retificação')),
                ('reserva_situacao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Reserva Situação')),
                ('reserva_area_averbada', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='RL Área Averbada')),
                ('reserva_area_nao_averbada', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='RL Área Não Averbada')),
                ('reserva_legal_proposta', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='RL Proposta')),
                ('reserva_legal_declarada', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='RL Declarada')),
                ('situacao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Situação CAR')),
                ('solo_area_nativa', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Solo - Área Nativa')),
                ('solo_area_uso', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Solo - Área Uso')),
                ('solo_area_servidao', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Solo - Área Servidão')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Cadastro Ambiental Rural',
            },
        ),
        migrations.CreateModel(
            name='Certificacao_Sigef_Parcelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Imóvel')),
                ('area_ha', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Área Ha')),
                ('detentor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Detentor')),
                ('cpf_cnpj_detentor', models.CharField(blank=True, max_length=50, null=True, verbose_name='CPF/CNPJ')),
                ('cns', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNS')),
                ('codigo_parcela', models.UUIDField(blank=True, null=True, verbose_name='Código Parcela')),
                ('matricula', models.CharField(blank=True, max_length=50, null=True, verbose_name='CNS')),
                ('data_entrada', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Parcelas Certificações SIGEF',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_Ambiental_Rural_Coordenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.cadastro_ambiental_rural', verbose_name='Imóvel Rural')),
            ],
            options={
                'verbose_name_plural': 'Coordenadas do CAR',
            },
        ),
        migrations.CreateModel(
            name='Cadastro_Ambiental_Rural_Restricoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('origem', models.CharField(blank=True, max_length=255, null=True, verbose_name='Origem da Restrição')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição da Restrição')),
                ('data_processamento', models.DateField(blank=True, null=True, verbose_name='Data Processamento')),
                ('area_conflito', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Área de Conflito')),
                ('percentual', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Percentual Área Conflito')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.cadastro_ambiental_rural', verbose_name='Imóvel Rural')),
            ],
            options={
                'verbose_name_plural': 'Restrições no CAR',
            },
        ),
        migrations.CreateModel(
            name='Certificacao_Sigef_Parcelas_Limites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('do_vertice', models.CharField(blank=True, max_length=100, null=True, verbose_name='Do Vértice')),
                ('ao_vertice', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ao Vértice')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo')),
                ('lado', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lado')),
                ('azimute', models.CharField(blank=True, max_length=100, null=True, verbose_name='Azimute')),
                ('comprimento', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Comprimento')),
                ('confrontante', models.TextField(blank=True, null=True, verbose_name='Confrontante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.certificacao_sigef_parcelas', verbose_name='Parcela')),
            ],
            options={
                'verbose_name_plural': 'SIGEF - Limites de Parcelas',
            },
        ),
        migrations.CreateModel(
            name='Certificacao_Sigef_Parcelas_Vertices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Código do Vértice')),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Longitude')),
                ('sigma_long', models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True, verbose_name='Sigma Long')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('sigma_lat', models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True, verbose_name='Sigma Lat')),
                ('altitude', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='Altitude')),
                ('sigma_altitude', models.DecimalField(blank=True, decimal_places=4, max_digits=4, null=True, verbose_name='Sigma Altitude')),
                ('metodo_posicionamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Método Posicionamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcela', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.certificacao_sigef_parcelas', verbose_name='Parcela')),
            ],
            options={
                'verbose_name_plural': 'SIGEF - Vértices de Parcelas',
            },
        ),
        migrations.CreateModel(
            name='Imoveis_Rurais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=255, null=True, verbose_name='Nome Imóvel')),
                ('matricula', models.CharField(max_length=100, null=True, verbose_name='Matrícula Imóvel')),
                ('livro_registro', models.CharField(max_length=150, null=True, verbose_name='Livro Registro')),
                ('numero_registro', models.CharField(max_length=150, null=True, verbose_name='Número Registro')),
                ('cns', models.CharField(blank=True, max_length=150, null=True, verbose_name='CNS')),
                ('data_registro', models.DateField(null=True, verbose_name='Data Registro')),
                ('cep', models.CharField(max_length=50, null=True, verbose_name='CEP Localização')),
                ('endereco', models.TextField(blank=True, null=True, verbose_name='Endereço da Fazenda')),
                ('titulo_posse', models.CharField(max_length=255, null=True, verbose_name='Título de Posse')),
                ('numero_nirf', models.CharField(max_length=100, null=True, verbose_name='Número NIRF')),
                ('codigo_imovel', models.CharField(max_length=100, null=True, verbose_name='Código Imóvel Rural')),
                ('codigo_car', models.CharField(max_length=150, null=True, verbose_name='Registro CAR')),
                ('area_total', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Área Total')),
                ('modulos_fiscais', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Módulos Fiscais')),
                ('area_reserva', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Área de Reserva Legal')),
                ('localizacao_reserva', models.CharField(choices=[('AM', 'Mesma Matrícula'), ('AE', 'Área Externa'), ('AP', 'Área Externa Parcial')], max_length=2, null=True, verbose_name='Localização da Reserva Legal')),
                ('area_app', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Área de APP')),
                ('area_veg_nat', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Área de Vegetação Nativa')),
                ('area_explorada', models.DecimalField(decimal_places=4, max_digits=15, null=True, verbose_name='Área Explorada')),
                ('roteiro_acesso', models.TextField(blank=True, null=True, verbose_name='Roteiro de Acesso')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('car', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.cadastro_ambiental_rural', verbose_name='CAR')),
                ('cartorio_registro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.cartorios_registro', verbose_name='Cartório Registro')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.municipios', verbose_name='Município')),
                ('proprietarios', models.ManyToManyField(to='cadastro.cadastro_pessoal', verbose_name='Proprietários')),
            ],
            options={
                'verbose_name_plural': 'Imóveis Rurais',
            },
        ),
        migrations.AddField(
            model_name='certificacao_sigef_parcelas',
            name='imovel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.imoveis_rurais', verbose_name='Imóvel Rural'),
        ),
        migrations.CreateModel(
            name='Imoveis_Rurais_Coordenadas_Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('latitude_gd', models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Latitude GD')),
                ('longitude_gd', models.DecimalField(decimal_places=12, max_digits=15, verbose_name='Longitude GD')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('imovel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.imoveis_rurais', verbose_name='Imóvel')),
            ],
            options={
                'verbose_name_plural': 'Coordenadas Matrícula Imóvel',
            },
        ),
        migrations.CreateModel(
            name='Regimes_Exploracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('regime', models.CharField(choices=[('PR', 'Próprio'), ('AR', 'Arrendamento'), ('CO', 'Comodato'), ('PA', 'Parceria'), ('AN', 'Anuência'), ('CCA', 'Condomínio com Anuência'), ('CSA', 'Condomínio sem Anuência')], max_length=3, null=True, verbose_name='Regime de Exploração')),
                ('data_inicio', models.DateField(null=True, verbose_name='Data de Início')),
                ('data_termino', models.DateField(null=True, verbose_name='Data de Término')),
                ('area', models.DecimalField(decimal_places=2, max_digits=15, null=True, verbose_name='Área Total Explorada')),
                ('atividades', models.CharField(choices=[('AGRI', 'Agricultura'), ('PEC', 'Pecuária'), ('AGP', 'Agricultura e Pecuária'), ('O', 'Outras')], max_length=5, null=True, verbose_name='Atividades Exploradas')),
                ('detalhamento', models.TextField(null=True, verbose_name='Detalhamento Regime Exploração')),
                ('instrumento_cessao', models.FileField(null=True, upload_to='farms/regimes/instrumento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('imovel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.imoveis_rurais', verbose_name='Imóvel Rural')),
                ('instituicao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.instituicoes_razao_social', verbose_name='Instituição')),
                ('quem_explora', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cadastro_pessoal', verbose_name='Quem Explora')),
            ],
            options={
                'verbose_name_plural': 'Regimes Exploração',
            },
        ),
        migrations.CreateModel(
            name='Regimes_Exploracao_Coordenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Longitude')),
                ('latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('regime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.regimes_exploracao', verbose_name='Regime Exploração')),
            ],
            options={
                'verbose_name_plural': 'Coordenadas Regime Exploração',
            },
        ),
    ]
