# Generated by Django 5.0 on 2024-07-01 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_initial'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imoveis_rurais',
            name='cartorio_registro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.cartorios_registro', verbose_name='Cartório Registro'),
        ),
    ]
